name: Python Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint flake8
        pip install -r requirements.txt
        
    - name: Run Flake8
      run: |
        PYTHONPATH=. flake8 cryri/
        
    - name: Run Pylint
      run: |
        PYTHONPATH=. pylint cryri/ 